spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatajpaaudit?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  main:
    banner-mode: off
logging:
  level:
    org:
      hibernate:
        sql: info






