spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nimatest?createDatabaseIfNotExist=true
    username: nimauser
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  main:
    banner-mode: console

logging:
  level:
    org:
      hibernate:
        sql: info






